---
# tasks file for docker

- name: Install Docker Dependencies
  apt:
    pkg:
    - apt-transport-https
    - ca-certificates
    - curl
    - software-properties-common
    - gnupg
    - lsb-release
    - python3
    - python3-pip
    - python-pip
    - python-setuptools
    state: latest
    update_cache: true
- name: Add Docker GPG Key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
- name: Add Docker APT Repository
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename|lower }} stable"
- name: Install Docker Engine
  apt:
    pkg:
    - docker-ce
    - docker-ce-cli
    - containerd.io
    update_cache: true
- name: Add ubuntu user to Docker group
  ansible.builtin.user:
    name: layekhakim
    groups: docker
    append: yes
- name: pip docker
  pip:
    executable: pip
    name: docker 

- name: Add a jenkins user
  ansible.builtin.user:
    name: jenkins
    groups: docker
    append: yes